### PR TITLE
add hashing

### PR DESCRIPTION
**Pull request by wagyourtail**
this one actually works :)

### CODE REVIEW

**Comment by JamesGreen31** [comment]
If you add the run condition below as a seperate workflow for the hashing:

  workflow_run:
    workflows:
      - Java CI with Gradle
    types:
      - completed
      
   #hashing stuff here

You can have the workflows wait for each other. That way we an visually see the separate workflows.

**Comment by wagyourtail** [comment]
why. it doesn't matter, it's separate artifact uploads anyway and this way they're actually visually associated with each-other.

**Comment by JamesGreen31** [comment]
The workflow is titled "Java CI with Gradle". I was trying to get the hashes one separate so we can see it generate. then again, it shouldn't ever fail, so I suppose it is un-necesarry. 

Good job on this! I'm not sure quite sure why mine didn't work when I took this same path. I like that you used the ubuntu shell to hash all the files. I wasn't sure how to do that in powershell, so I planned to hash the whole artifacts file.

**Comment by JamesGreen31** [comment]
Where do we go to download the artifacts? Is there a way to embed that link into the readme?

**Pull request merged**
