### PR TITLE
Auto-hash attempt 1

### PR DESCRIPTION
**Pull request by JamesGreen31**
attempt number 1

### CODE REVIEW

**Comment by wagyourtail** [comment]
`runs-on: windows-2019`

:vomiting_face:

**Comment by wagyourtail** [comment]
also this won't work because the artifact is created on a different action so that `download build artifact` can't see it also it won't wait for that action to complete and upload the artifact

**Comment by wagyourtail** [comment]
also you should be able to test the actions on your own fork yourself...

**Comment by JamesGreen31** [comment]
> also this won't work because the artifact is created on a different action so that `download build artifact` can't see it also it won't wait for that action to complete and upload the artifact

It has to run on windows-2019 for certutil to work. Also, W2019 isn't that bad lol.

As for it not being able to download, do you have any suggestions for how to pull the other one out?

**Comment by JamesGreen31** [comment]
> also you should be able to test the actions on your own fork yourself...

It won't run the builds on my fork for any of the workflows

**Comment by JamesGreen31** [comment]
Closing as wag your tail beat me to it

**Pull request closed without merging**
