### PR TITLE
1.18 Support for altoclef

### PR DESCRIPTION
**Pull request by lolo45654**
#135 mentioned it first, 1.18 came out and this is the pull request for 1.18 altoclef.
This is my second pull request (the first is on [gaucho-matrero/baritone](https://github.com/gaucho-matrero/baritone/)).

### CODE REVIEW

**Comment by Bluscream** [comment]
Do you got an artifact for me?

**Comment by lolo45654** [comment]
@Bluscream [latest release](https://github.com/lolo45654/altoclef/releases/latest)
It worked for me, tell me if something went wrong.

**Comment by Bluscream** [comment]
> @Bluscream [my latest release link](https://github.com/lolo45654/altoclef/releases/latest) It worked for me, tell me if something went wrong.

thanks :) sadly my mc didn't like it: https://paste.ee/p/nRtb1

**Comment by lolo45654** [comment]
Please open an issue [here](https://github.com/lolo45654/altoclef/issues), everything should have its place 😄 But i think i can already help you, I think you have baritone in the mods folder, altoclef delivers baritone within, so there's an conflict

**Comment by Bluscream** [comment]
> Please open an issue [here](https://github.com/lolo45654/altoclef/issues), everything should have its place 😄 Altoclef delivers baritone within, so there's no need for an extra baritone installation.

OHHH, thanks for letting me know

**Comment by Bluscream** [comment]
Got a crash without baritone now, https://paste.ee/p/wVbXw

I wonder if it still belongs in the baritone repo, since the stacktrace says 

```
[02:43:29] [Render thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26204()" because "current" is null
	at baritone.process.BuilderProcess.valid(BuilderProcess.java:829) ~[baritone-1.18-SNAPSHOT-98b3823201e5a8a9.jar:?]
	at baritone.process.BuilderProcess.onTick(BuilderProcess.java:485) ~[baritone-1.18-SNAPSHOT-98b3823201e5a8a9.jar:?]
	at baritone.utils.PathingControlManager.executeProcesses(PathingControlManager.java:200) ~[baritone-1.18-SNAPSHOT-98b3823201e5a8a9.jar:?]
	at baritone.utils.PathingControlManager.preTick(PathingControlManager.java:89) ~[baritone-1.18-SNAPSHOT-98b3823201e5a8a9.jar:?]
	at baritone.behavior.PathingBehavior.onTick(PathingBehavior.java:98) ~[baritone-1.18-SNAPSHOT-98b3823201e5a8a9.jar:?]
	at baritone.event.GameEventHandler.lambda$onTick$0(GameEventHandler.java:59) ~[baritone-1.18-SNAPSHOT-98b3823201e5a8a9.jar:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
	at baritone.event.GameEventHandler.onTick(GameEventHandler.java:59) ~[baritone-1.18-SNAPSHOT-98b3823201e5a8a9.jar:?]
	at net.minecraft.class_310.handler$zbe000$runTick(class_310.java:4036) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1720) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1086) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [intermediary-minecraft-1.18-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) [fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by lolo45654** [comment]
Again, [open an issue if you have one](https://github.com/lolo45654/altoclef/issues).
I tried with the mods you have installed, but everything works fine for me. Steps to reproduce? Try maybe without Multimc?

**Comment by Bluscream** [comment]
https://github.com/wagyourtail/baritone/actions

**Comment by Bluscream** [comment]
This is fixed

**Pull request closed without merging**
